### ISSUE TITLE
FakeSftpServerRule.createDirectory should accept a varargs parameter

### ISSUE THREAD

**Issue by helpermethod** [stefanbirkner/fake-sftp-server-rule#3]
Hi,

it would be awesome if `createDirectory` would accept a varargs String parameter, something like

```java
public void createDirectory(String... paths) throws IOException {
    this.verifyThatTestIsRunning("create directory");
    Arrays.stream(paths).forEach(path -> {
        Path pathAsObject = this.fileSystem.getPath(path, new String[0]);
        Files.createDirectories(pathAsObject, new FileAttribute[0]);
    });
}
```

This way, the method would still be backwards compatible but creating multiple directories would be simplified.

**Comment by stefanbirkner** [comment]
Hi Oliver,

thanks for the feature request. I'm thinking about creating a second method `createDirectories(String... paths)` for that feature. This is because other APIs create a folder `a/b/c` when you call `createDirectory("a", "b", "c");` and I don't want to confuse the users. What do you think about the method name `createDirectories`?

**Comment by helpermethod** [comment]
Sounds perfect!
